version: '4.40'
services:
  postgres:
    container_name: postgre
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gusta
      POSTGRES:08: docker-agendadb
    ports:
      - '5433:5433'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gustavocruz.profissional@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '80:80'
    depends_on:
      - postgres
    networks:
      - backend
  dockeragendaentregas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    container_name: dockeragendaentregas
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.application.name" : "AgendaEntregas"
       "spring.datasource.driver-class-name" : "org.postgresql.Driver"
       "spring.datasource.url" : "jdbc:postgresql://localhost:5432/AgendamentoEntrega_db"
       "spring.datasource.username" : "postgres"
       "spring.datasource.password" : "gusta"
       "spring.jpa.hibernate.ddl-auto" : "none"
       ".jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect"
       "spring.jpa.show-sql" : "false"
       "spring-doc.paths-to-match" : "/entrega/**"
       "spring-doc.swagger-ui.use-root-path" : "true"
      }'
    depends_on:
      - postgres
      - pgadmin
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  pg-data: