ALTER TABLE public.entrega OWNER TO postgres;

--
-- Name: entrega_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entrega ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entrega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: entrega; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.entrega (id, data_entrega, endereco, items, nome_cliente, numero_cliente) FROM stdin;
3	2025-04-30 14:30:00	4a Travessa da Glória, 16	Meu coração	Paloma	71986248527
\.



--
-- Name: entrega_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entrega_id_seq', 3, true);


--
-- Name: entrega entrega_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entrega
    ADD CONSTRAINT entrega_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--
