spring:
  application:
   name: AgendaEntregas
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AgendamentoEntrega_db
    username: postgres
    password: gusta
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
spring-doc:
  paths-to-match: /entrega/**
  swagger-ui:
    use-root-path: true